modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cc_sable"
version = "${version}"
displayName = "CC: Sable"
authors = "TechTastic"
description = '''
CC: Tweaked addon for Sable!
'''
#logoFile = ""

[[dependencies.cc_sable]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cc_sable]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cc_sable]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cc_sable.mixins.json"
