name: Build & Publish Docs

on:
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install LDoc
        run: |
          sudo apt-get install -y lua5.4 luarocks
          sudo luarocks install ldoc

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate docs
        run: |
          VERSION=${{ github.event.release.tag_name }}
          mkdir gh-pages/$VERSION
          ldoc -c docs/config.ld -d gh-pages/$VERSION .

      - name: Generate versions.json
        run: ls -d gh-pages/v* | jq -R gh-pages/. | jq -s gh-pages/. > gh-pages/versions.json

      - name: Copy over version.js
        run: cp docs/version.js gh-pages/version.js

      - name: Script Injection for Dropdown
        run: find gh-pages/ -name "*.html" -exec \ sed -i '/<\/body>/i <script src="\/version.js"><\/script>' {} \;

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: add ${{ steps.version.release.tag_name }}"
          git push